.github/workflows/release.yml
Changing CI so that `neurotechdevkit` is published to the main PyPi repo
=> Releasing to pypi main repo

README.md, docs/contributing.md, docs/index.md
This PR extends the installation instructions mentioning the need of installing libomp and defining the DEVITO_ARCH environment variable
=> Mentioning libomp in the installation instructions

.github/workflows/release.yml
As `main` is now a protected branch, it's impossible to commit and push the new poetry version. 
For this reason, the Personal Access Token has to be used.
=> Adding Personal Access Token to push release

docs/examples/plot_adding_custom_source.py, docs/examples/plot_metrics.py, src/neurotechdevkit/__init__.py
In this PR two new notebooks were added, one shows the simulation metrics, and the other one shows how an user can add a custom source to the simulation
=> Add example notebooks to the gallery

docs/usage/gpu.md, mkdocs.yml, src/neurotechdevkit/scenarios/_base.py
This PR documents how a user can run the NDK simulation using the GPU #32 . 
This code was tested in an AWS instance with NVIDIA HPC preinstalled:
```
PLATFORM='nvidia-acc' python plot_full_scenario.py 
creating a grid with shape: (241, 141) for extent: [0.12 0.07] m
Estimated time to complete simulation: 47 seconds. Memory required is 8 GB (available 64.264081408 GB). These values are approximated.
Default Devito configuration:
* autotuning=off
* develop-mode=False
* mpi=False
* log-level=DEBUG
* language=openmp
(ShotID 0) Preparing to run state for shot
(ShotID 0) Estimated bandwidth for the propagated wavelet 0.497-0.502 MHz
(ShotID 0) Spatial grid spacing (0.500 mm | 5.981 PPW) is below dispersion limit (0.598 mm | 5.000 PPW)
(ShotID 0) Time grid spacing (0.083 μs | 46%) is above OT2 …
```
=> Adding GPU support documentation

docs/index.md, mkdocs.yml
After getting the following error when running a 3D simulation:
```
Undefined symbols for architecture x86_64:
"_omp_get_thread_num", referenced from:
_acoustic_iso_state in eb9e3f74a93b6949c2bedccf28c75a01c539ee0d-c5907e.o
ld: symbol(s) not found for architecture x86_64
```
we've come up with new instructions on how to properly install NDK's dependencies into MacOS
=> Updating instructions for MacOS installation

.circleci/config.yml, .github/workflows/trigger_gallery_build.yml
Scheduling an action to trigger a circleCI build of the whole gallery
Triggered build: https://app.circleci.com/pipelines/github/agencyenterprise/neurotechdevkit/341/workflows/928a9dbf-dc2e-447b-bbda-cab93f5efb9b/jobs/277
=> Adding cronjob triggering circleCI to build the gallery examples without cache

.circleci/config.yml
We should not execute the `default` CircleCi job when github action triggers the doc build with no cache:
https://app.circleci.com/pipelines/github/agencyenterprise/neurotechdevkit/386
=> Preventing execution of cached docs job when uncached job is running

src/neurotechdevkit/results/_metrics.py, src/neurotechdevkit/results/_results.py, tests/neurotechdevkit/scenarios/test_metrics.py, tests/neurotechdevkit/scenarios/test_results.py
As metrics are extracted from a Result object it makes sense to have them within the `results` folder
=> Moving _metrics.py to results folder

.github/workflows/test.yml
With the python version in the cache key we will force libraries to be installed when a new python version is used
The newly created cache keys are visible here: https://github.com/agencyenterprise/neurotechdevkit/actions/caches
=> Adding python version to cache key

Dockerfile
This pull request addresses https://github.com/agencyenterprise/neurotechdevkit/issues/106.
The issue describes a bug where running the plot_pulsed_simulation.ipynb example notebook from the prebuilt docker container results in an error when trying to create an animation video due to the missing ffmpeg dependency. This pull request adds ffmpeg to the docker dependencies to resolve the issue.
The following changes have been made in this pull request:
* Added ffmpeg to the docker dependencies.
The new behavior introduced by this pull request is that the plot_pulsed_simulation.ipynb example notebook will now be able to create the animation.mp4 file successfully, as ffmpeg will be available in the docker container.
To test this change:
* Pull the latest version of the repository.
* Build and …
=> Add ffmpeg to docker dependencies

.github/workflows/lint.yml, docs/examples/plot_3d.py, docs/usage/troubleshooting.md, src/neurotechdevkit/rendering/napari.py
https://github.com/agencyenterprise/neurotechdevkit/issues/119
`napari` is an optional dependency for 3D visualizations. The instructions use `napari[all]`, which installs `PyQt5` GUI backend, but `Qt5` is not supported on Mac M1.
This updates the documentation to install `napari` with `PyQt6` on Mac M1.
`plot_3d.py` can run on a Mac M1 after following documentation instructions to `pip install "napari[pyqt6_experimental]"`. Tested by running on my Mac M1. Screenshot:
=> Update `napari` install instructions to Qt6 on Mac M1

Dockerfile-gpu
Docker is a great way to get up and running but the current Dockerfile does not support GPUs.  This PR adds a Dockerfile-gpu which adds GPU support.
* Add Dockerfile-gpu
* Update Dockerfile `ENV PATH` to add an absolute reference to the venv bin directory.
The new cpu container works regardless of the directory the user is in.  For example, if running VS Code Dev Containers the default mount is /workspaces/  so the new absolute path points to the correct python interpreter.  The GPU Dockerfile creates a new container that supports GPUs.  This was verified by looking at the output of `simulate_steady_state` and noting the platform.
=> Add Dockerfile-gpu (#112)

src/neurotechdevkit/scenarios/_scenario_0.py
Noticed there was a typo with the type-hint being written as a default value:
```python
def _compile_problem(self, center_frequency=float) -> stride.Problem:
```
Changed to type hint (same as other scenarios):
```python
def _compile_problem(self, center_frequency: float) -> stride.Problem:
```
=> fix typo: type-hint vs default-value

docs/examples/plot_full_scenario.py, src/neurotechdevkit/scenarios/_base.py
With the changes made on PR https://github.com/agencyenterprise/neurotechdevkit/pull/82 the problem is only compiled when a simulation is executed, and not when the scenario is created. 
This prevents the render_layout function from being called before a simulation was executed.
The render_layout function is now compiling the problem if it was not compiled before
=> Compiling problem on render_layout if it was not compiled previously

src/neurotechdevkit/scenarios/built_in/_scenario_2.py
Scenario 2 is based on benchmark 8 of [Aubry et al. (2022)](https://pubs.aip.org/asa/jasa/article/152/2/1003/2838380/Benchmark-problems-for-transcranial-ultrasound). NDK provides a 2D variant that is supposed to correspond to the slice through the transducer.
Fixes the slice index for benchmark 8's 2D variant to match the paper description:
> Using 1-based indexing, the center of the source (rear of the bowl or center of the piston) relative to the output grid was positioned at... [1, 171, 191] for benchmark 8.
This also happens to be the middle slice: `.shape[2] // 2`. The 3-D `mask.shape` is `(451, 341, 381)`
TODO:
=> Fix slice index for benchmark-8 2D

src/neurotechdevkit/results/_metrics.py, src/neurotechdevkit/results/_results.py, src/neurotechdevkit/scenarios/__init__.py, src/neurotechdevkit/scenarios/_base.py, src/neurotechdevkit/scenarios/_utils.py, src/neurotechdevkit/scenarios/built_in/_scenario_0.py, src/neurotechdevkit/scenarios/built_in/_scenario_1.py, src/neurotechdevkit/scenarios/built_in/_scenario_2.py, tests/neurotechdevkit/scenarios/test_results.py
https://github.com/agencyenterprise/neurotechdevkit/issues/134
This PR adds the `get_steady_state_result_2d` method to the `SteadyStateResult3D` class to be able to convert the `SteadyStateResult3D` output of a 3-D simulation to a `SteadyStateResult2D` that just encapsulates the slice of interest.
The `get_steady_state_result_2d` method with optional arguments of `slice_axis` and `slice_position` (the `slice_axis` and `slice_position` property of the 3D result is used when none is given) is added to the `SteadyStateResult3D` class in `_results.py`. The method `_validate_slice_args` is also added to `SteadyStateResult3D` to check the slice being made. The `SteadyStateResult2D` object returned by the `get_steady_state_result_2d` method has the target and sources removed (should be changed …
=> 134 Slice `SteadyStateResult3D` to `SteadyStateResult2D`

.circleci/config.yml, mkdocs.yml, poetry.lock, pyproject.toml
https://github.com/agencyenterprise/neurotechdevkit/issues/141
We use CircleCI to generate docs webpages for every pull request. This is particularly helpful to view for pull requests that add or edit `docs/examples `scripts.
Unfortunately, our current PR/CircleCI docs do not include figures, showing them only as broken links, e.g.:
The root cause appears to be an issue with the paths, as a local build (which shows images correctly) puts, e.g. the `plot_time_reverse` page at 
`http://127.0.0.1:8000/neurotechdevkit/generated/gallery/plot_time_reverse/` but then on CI, it shows up not in its own folder but as:
`https://output.circle-artifacts.com/output/job/a9676679-2d73-455d-a473-c666c02fa461/artifacts/0/html/generated/gallery/plot_time_reverse.html`
This appears to be the result of a …
=> Include gallery images in CircleCI-generated docs

Makefile
`make spellcheck` relies on `pyenchant`, which fails on Apple Silicon Mac (e.g., M1) to find the `C enchant` library: https://github.com/pyenchant/pyenchant/issues/265
This shows up as a `en_US`-not-found error on my M1 Mac.
When running `make spellcheck`, it now also prints this recommended workaround:
```shell
❯ make spellcheck
poetry run pylint --disable all --enable spelling --spelling-dict en_US --spelling-private-dict-file=whitelist.txt src
```
Given that the number of users using Apple Silicon Mac will increase (as Apple phases out x86) and that only NDK developers (not users) will run `make spellcheck`, I think it's reasonable to surface this directly in the command, instead of making the `Makefile` comment silent.
After adding `export …
=> Document spellcheck issue on Mac M1

src/neurotechdevkit/imaging/beamform.py, tests/neurotechdevkit/imaging/test_beamform.py
Bugfix: the `beamform.py` code expects an `interp` dimension, even though this is not added in the nearest-neighbors interpolation method 
* Add singleton `interp` dimension to the nearest-neighbors matrix construction
* Test nearest-neighbors interpolation code-path in unit tests
* New unit test passes
=> Add interp dimension in nearest-neighbors interpolation to match linear interpolation

.circleci/config.yml
The repo size is getting bigger because our documentation is quite heavy.
Using the gh-pages flag that deletes the parent history before comiting the docs.
=> Push force new docs commit without parent history

.circleci/config.yml
CI failed on main because the flag added on [PR](https://github.com/agencyenterprise/neurotechdevkit/pull/183) is not supported on that package version
Updating gh-pages dependency version
=> Updagrading gh-pages package so it supports --no-history

docs/examples/plot_time_reverse.py, src/neurotechdevkit/rendering/colormaps.py, src/neurotechdevkit/results/_metrics.py, src/neurotechdevkit/results/_results.py, src/neurotechdevkit/scenarios/built_in/_scenario_1.py, src/neurotechdevkit/sources.py, tests/neurotechdevkit/scenarios/test_metrics.py
https://github.com/agencyenterprise/neurotechdevkit/issues/171
Introduction from `plot_time_reverse.py`:
> The skull adds aberrations to the beam propagation; phased arrays can compensate for those by having different delays for each element, but estimating these delays can be challenging. One method to estimate the delays is a "time reverse" simulation as described in this [Article](https://koreascience.kr/article/JAKO200612242715181.pdf). This notebook demonstrates the "time reverse" method to estimate the delays. The notebook sets up a scenario with a phased array source and a target and then runs a simulation with the source and target reversed to calculate the delays. Finally, it uses the calculated delays to perform a forward-time simulation.
The time-reverse simulation was still …
=> Fix plot_time_reverse.py time-reverse simulation

Dockerfile, Dockerfile-gpu, docs/contributing.md, docs/index.md, docs/installation.md
As big image files were moved to AWS the links have to be updated to point to AWS.
=> Fixing links of the gallery

src/neurotechdevkit/imaging/beamform.py
Previously, the `beamform_delay_and_sum()` implementation did not properly handle the case where `iq_signals` has an extra batch dimension for echoes, so downstream computations did not work due to shape mismatch.
This PR modifies the implementation to properly handle the cases when `iq_signals` has an echoes dimensino and also when it doesn't.
=> Fix beamforming batching
