agencyenterprise/neurotechdevkit

README.md
I took the text from the documentation and placed it at the top of the README file. I also removed "Research" from the title.
=> Update README with text from docs landing page

poetry.lock, pyproject.toml
Downgrading mkdocs gallery, newer version requires missing configuration
=> Downgrading mkdocs gallery

.circleci/config.yml
Build docs for pull requests and save them as artifacts using circle CI.
=> Build docs on circle ci

docs/index.md
Replacing mkdocs markup with markup, so that README.md is correctly rendered in the github main page and also in PyPi
=> Fix readme

.github/workflows/test.yml
=> Adding codecov to CI

Makefile
=> Fixing codecov

.github/workflows/test.yml, Makefile
Defining output of pytest coverage
=> Configuring pytest coverage output

Makefile, poetry.lock, pyproject.toml, src/neurotechdevkit/__init__.py, src/neurotechdevkit/rendering/__init__.py, src/neurotechdevkit/rendering/_animations.py, src/neurotechdevkit/rendering/_formatting.py, src/neurotechdevkit/rendering/_source.py, src/neurotechdevkit/rendering/_target.py, src/neurotechdevkit/rendering/colormaps.py, src/neurotechdevkit/rendering/font.py, src/neurotechdevkit/rendering/layers.py, src/neurotechdevkit/rendering/layout.py, src/neurotechdevkit/rendering/legends.py, src/neurotechdevkit/rendering/napari.py, src/neurotechdevkit/rendering/simulations.py, src/neurotechdevkit/scenarios/__init__.py, src/neurotechdevkit/scenarios/_base.py, src/neurotechdevkit/scenarios/_metrics.py, src/neurotechdevkit/scenarios/_resources.py, src/neurotechdevkit/scenarios/_results.py, src/neurotechdevkit/scenarios/_scenario_0.py, src/neurotechdevkit/scenarios/_scenario_1.py, src/neurotechdevkit/scenarios/_scenario_2.py, src/neurotechdevkit/scenarios/_shots.py, src/neurotechdevkit/scenarios/_time.py, src/neurotechdevkit/scenarios/_utils.py, src/neurotechdevkit/scenarios/materials.py, src/neurotechdevkit/sources.py
Adding `codespell` and `pydocstyle` to project.
The checkers were added to the make file and are automatically executed on CI
=> Add spellchecker

.github/workflows/release.yml
Adding conditional to publish_release job
=> Only running publish release if a new version was generated

.github/workflows/release.yml
Small change to test version bump
=> Removing empty lines to test version bump

pyproject.toml
Removes "research" from project description
=> update project description

docs/index.md, docs/usage/troubleshooting.md, mkdocs.yml
This PR adds a troubleshooting section to the docs containing the known problems a user might face when installing or when using NDK
=> Adding troubleshooting section

.github/workflows/lint.yml, Makefile, poetry.lock, pyproject.toml, src/neurotechdevkit/rendering/_animations.py, src/neurotechdevkit/rendering/_formatting.py, src/neurotechdevkit/rendering/_source.py, src/neurotechdevkit/rendering/_target.py, src/neurotechdevkit/rendering/layers.py, src/neurotechdevkit/rendering/layout.py, src/neurotechdevkit/rendering/legends.py, src/neurotechdevkit/rendering/napari.py, src/neurotechdevkit/rendering/simulations.py, src/neurotechdevkit/scenarios/_base.py, src/neurotechdevkit/scenarios/_scenario_0.py, src/neurotechdevkit/scenarios/_shots.py, src/neurotechdevkit/scenarios/_time.py, src/neurotechdevkit/scenarios/_utils.py, src/neurotechdevkit/sources.py, tests/neurotechdevkit/test_sources.py
Fixing all warnings encountered by pyright and adding pyright to CI
=> Pyright integration

docs/api/make.md, docs/api/results.md, docs/api/scenarios.md, docs/api/sources.md, docs/css/mkdocstrings.css, mkdocs.yml, src/neurotechdevkit/__init__.py, src/neurotechdevkit/rendering/_formatting.py, src/neurotechdevkit/rendering/_source.py, src/neurotechdevkit/rendering/_target.py, src/neurotechdevkit/rendering/layers.py, src/neurotechdevkit/rendering/layout.py, src/neurotechdevkit/rendering/legends.py, src/neurotechdevkit/rendering/napari.py, src/neurotechdevkit/rendering/simulations.py, src/neurotechdevkit/results/__init__.py, src/neurotechdevkit/results/_results.py, src/neurotechdevkit/scenarios/__init__.py, src/neurotechdevkit/scenarios/_base.py, src/neurotechdevkit/scenarios/_metrics.py, src/neurotechdevkit/scenarios/_results.py, src/neurotechdevkit/scenarios/_scenario_1.py, src/neurotechdevkit/scenarios/_scenario_2.py, src/neurotechdevkit/scenarios/_shots.py, src/neurotechdevkit/scenarios/_time.py, src/neurotechdevkit/scenarios/_utils.py, src/neurotechdevkit/sources.py, tests/neurotechdevkit/scenarios/test_base.py, tests/neurotechdevkit/scenarios/test_metrics.py, tests/neurotechdevkit/scenarios/test_results.py
Updating docstrings so it's correctly rendered on the API docs
=> Fixing docstrings to make API rendering correct

.circleci/config.yml, .github/pull_request_template.md, .github/workflows/circle_artifacts.yml
Adding a job that gets the CircleCI artifacts link, making it much easier to check the PR generated docs
=> Adding job to display a link to the PR generated documentation

.github/workflows/docs.yml, .github/workflows/test.yml
This PR adds python 3.10 as CI target
=> Adding python 3.10 as CI testing target

docs/examples/plot_store_results.py
This PR shows how a simulation can be stored in a file and how it can be loaded and rendered afterward. #33
=> Adding example of save and load results

docs/usage/troubleshooting.md
Extending troubleshooting with known installation problems
#56
=> Extending troubleshooting

docs/index.md, docs/usage/installation.md, mkdocs.yml
This PR moves the local installation documentation to its own page https://github.com/agencyenterprise/neurotechdevkit/issues/57
=> Split installation methods in docs

.circleci/config.yml, .github/workflows/docs.yml, .github/workflows/lint.yml, .github/workflows/release.yml, .github/workflows/test.yml
=> Caching in CI

.github/workflows/lint.yml, .github/workflows/test.yml
Using correct cache folder for poetry dependencies
=> Updating CI cache folder

.github/workflows/release.yml
With this PR we will not release the package if the tests and lint are not passing
=> Preventing release before tests are passing

.circleci/config.yml, docs/api/scenarios.md, docs/api/utils.md, docs/examples/plot_full_scenario.py, mkdocs.yml, src/neurotechdevkit/scenarios/__init__.py, src/neurotechdevkit/scenarios/_base.py, src/neurotechdevkit/scenarios/_scenario_0.py, src/neurotechdevkit/scenarios/_scenario_1.py, src/neurotechdevkit/scenarios/_scenario_2.py, src/neurotechdevkit/scenarios/_utils.py, tests/neurotechdevkit/scenarios/test_base.py
In this PR scenario 1 was simplified and added to the gallery to show how a user can add a new scenario #35 
Some functions were made public to the NDK package so they can be used by a scenario implementer, these functions are now exposed in the API docs as well
=> Document full scenario

docs/usage/installation.md
Extending the installation instructions for MacOS users
=> Adding extra instructions to MacOS users installing neurotechdevkit

docs/usage/installation.md
Adding instructions on how to install neurotechdevkit on Windows (using WSL)
It seems like devito was never tested on Windows -> https://github.com/devitocodes/devito/wiki/Installation-Issues#windows
=> Adding Windows installation instructions

.github/workflows/test.yml, tests/neurotechdevkit/test_compilation.py
Added test that exercises the compilation path.
Running integration tests on CI
=> Adding integration test with compilation to CI

docs/index.md
includes better NDK vision to readme
=> update readme text

docs/examples/plot_3d.py, docs/index.md, docs/installation.md, docs/usage/troubleshooting.md, mkdocs.yml
Various small fixes to docs
PS: we need to sync this PR with https://github.com/agencyenterprise/neurotechdevkit/pull/76 as the link to the installation page should be updated on PR 76
=> Various improvements to docs

docs/contributing.md, docs/installation.md, docs/usage/troubleshooting.md
Adding documentation for ARM computers running MacOS.
Cleaning up `contributing` section.
=> Improving docs for ARM MacOS

.circleci/config.yml, .github/workflows/circle_artifacts.yml
Renaming circle_ci job and using it on the github job that generates the link for docs
=> Renaming circle_ci job

docs/examples/plot_homer.py
Fixed an image link in the docs that had 404'd.
=> changed link

.circleci/config.yml
Updating the node version used to push generated docs.
=> Updating node

.circleci/config.yml
Downgrading gh-pages packages because of this bug https://github.com/tschaub/gh-pages/issues/354
=> Downgrading gh-pages as it has a bug with find-cache
